### PR TITLE
Routing and Navigation for React

### PR DESCRIPTION
**Pull request by AbhinavReddy-Dev**
Added below for React
- Routing 
- Navigation
- Pages folder

### CODE REVIEW

**Review by DevangRaval1 — APPROVED** [review]
LGTM!

**Comment by briswells** [comment]
@AbhinavReddy-Dev is there a reason you added .js versions of the models in this merge? I feel like these should be kept out of the repo as they can be recreated by compiling the typescript.

**Review by hardikpatil — DISMISSED** [review]

**Comment by DevangRaval1** [comment]
Works without the .js files in models

**Review by DevangRaval1 — APPROVED** [review]

**Review by hardikpatil — APPROVED** [review]
Works on my end as well.

**Pull request merged**
