### PR TITLE
Placeholder Frontend tests  

### PR DESCRIPTION
**Pull request by chetan2298**
This is a commit for sample testcases of 2 frontend components sale and donor . 

-Infrastructure has been added to perform unit test cases for frontend code.
-JsDom has been specified as the testenv so that all tests run in a jsdom environment to allow tests to simulate a browser env and interact with DOM.
-swc is the jest transformer used to convert the code to plain js before jest can execute it

Contributors - @Anoushka444 @TanviMahajan11 @chetan2298

### CODE REVIEW

**Review by rohitkarhadkar — APPROVED** [review]
frontend_test
LGTM!!

**Review by sourabhk25 — APPROVED** [review]
The code looks good to me.
Executed changes on Docker - 
Screen Shot 2023-04-18 at 4 46 44 PM

**Comment by chetan2298** [comment]
Reviews by: @rohitkarhadkar @sourabhk25 
Basic Unit test cases for added for frontend code frontend code.

**Comment by G1411** [comment]
Screenshot 2023-04-18 at 5 11 46 PM

Yup, everything looks good!

**Pull request merged**
