### PR TITLE
Setup authentication stacks closing #118

### PR DESCRIPTION
**Pull request by briswells**
Everything is finally working together. On an login request frontend sends a post to backend who returns a JWT which gets set in local storage. When the front end calls an API route the JWT get added to the headers which the backend will use to check authentication. The token will remain until it expires allowing the user to remain logged in for the duration. The login state is being stored in a redux slice. When the app loads it checks for a valid token and if one is found sets the current user to logged in. This lets the user refresh the page and remain logged in. I'm sure there are better ways to implement this but I couldn't figure them out as I'm not a front end expert. 

When the user logs out the token is removed from their local storage.

The main issue I can see right now is on a refresh other values in the userSlice are deleted, but this probably could be solved with a route to the backend that retrieves the information on a refresh. Tokens are also not removed server side until they expire, this means after someone logs out the server still would accept their token, but this can be figured out at a later point.

### CODE REVIEW

**Review by MSS-Shalavritha — APPROVED** [review]
Hi @briswells, Just tested the PR, it is working as expected now. Attaching the docker log screenshot for your reference.
Screenshot 2023-04-20 at 9 53 38 PM

**Comment by hardikpatil** [comment]
I am not able to get pass through :/ 

Screenshot 2023-04-21 at 10 20 54

**Comment by hardikpatil** [comment]
> Hi @briswells, Just tested the PR, it is working as expected now. Attaching the docker log screenshot for your reference. Screenshot 2023-04-20 at 9 53 38 PM

@MSS-Shalavritha in what context?

**Comment by MSS-Shalavritha** [comment]
> > Hi @briswells, Just tested the PR, it is working as expected now. Attaching the docker log screenshot for your reference. Screenshot 2023-04-20 at 9 53 38 PM
> 
> @MSS-Shalavritha in what context?

As @briswells mentioned, I tested on freshly built container yesterday, logged in and navigated to different webpages, it was working as expected, I retested it again today without building a new container, it still seems to be working fine. Attaching the screenshot for your reference.
Screenshot 2023-04-21 at 11 58 03 AM

**Comment by AbhinavReddy-Dev** [comment]
@briswells @MSS-Shalavritha what are the login credentials to verify this? Can someone please provide them, I can't login from React frontend: 3000 port.

**Comment by MSS-Shalavritha** [comment]
> @briswells @MSS-Shalavritha what are the login credentials to verify this? Can someone please provide them, I can't login from React frontend: 3000 port.

Hi

> @briswells @MSS-Shalavritha what are the login credentials to verify this? Can someone please provide them, I can't login from React frontend: 3000 port.

@AbhinavReddy-Dev, Credentials, I'm using are:

Username: johndoe@example.com
Password : password

**Review by AbhinavReddy-Dev — APPROVED** [review]
Works for me with the credentials mentioned above.

**Comment by hardikpatil** [comment]
> > @briswells @MSS-Shalavritha what are the login credentials to verify this? Can someone please provide them, I can't login from React frontend: 3000 port.
> 
> @AbhinavReddy-Dev, Credentials, I'm using are:
> 
> Username: [johndoe@example.com](mailto:johndoe@example.com) Password : password

worked with these credentials though!

**Review by hardikpatil — APPROVED** [review]

**Review by MSS-Shalavritha — APPROVED** [review]

**Pull request merged**
