### PR TITLE
Expiry table test cases

### PR DESCRIPTION
**Pull request by KishoreMenda**
Added test cases for Expriy Table in Expiry page.

This PR is related to #238

### CODE REVIEW

**Review by rohitkarhadkar — APPROVED** [review]
expiry
LGTM!!!!

**Review by chetan2298 — APPROVED** [review]
Works as expected!
image

**Review by shmansa — COMMENTED** [review]
Looks Good To Me!

**Review by manavi-ghorpade-24 — COMMENTED** [review]
LGTM!

**Pull request merged**
