### PR TITLE
Added test cases for frontend.

### PR DESCRIPTION
**Pull request by rohitraut18**
Component -> Login
This code tests the successful submission of a login form using React Testing Library and a Redux store.
login test

### CODE REVIEW

**Review by rohitkarhadkar — DISMISSED** [review]
login
LGTM!!

**Comment by rohitkarhadkar** [comment]
email
The test cases check if the EmailResetComponent renders correctly with form fields, displays an error message for an invalid email or empty email input, and navigates to the verify page when a valid email is entered and the "Get Code" button is clicked.

**Comment by Manavi-ghorpade** [comment]
LGTM!

**Review by Manavi-ghorpade — APPROVED** [review]

**Review by shubhamlatkar — DISMISSED** [review]
LGTM
image

**Review by Manavi-ghorpade — APPROVED** [review]

**Review by shubhamlatkar — APPROVED** [review]
LGTM
image

**Review by chetan2298 — APPROVED** [review]
Works as expected!
image

**Pull request merged**
