### PR TITLE
Updates #118 by making API login Post action return json

### PR DESCRIPTION
**Pull request by briswells**
Backend will now return if the login is a success or failure, forward any authentication error messages, and return user email for on successful logins. More user info can be added later if needed. Route also sets a session cookie that can be used to check all other API routes that require authentication.

### CODE REVIEW

**Review by jayrevolinskyjr — APPROVED** [review]
Nice, works for me

**Review by hardikpatil — APPROVED** [review]
worked on `3001`

Screenshot 2023-04-17 at 00 57 21
Screenshot 2023-04-17 at 00 57 43

**Comment by briswells** [comment]
@hardikpatil @jayrevolinskyjr Reviews dismissed after rebase. Can you approve again please?

**Review by jayrevolinskyjr — APPROVED** [review]
LGTM, works on my system

**Pull request merged**
