### PR TITLE
Connect New FrontEnd To New BackEnd

### PR DESCRIPTION
**Pull request by prestonmasseyblake**
added a basic test

### CODE REVIEW

**Comment by Jooms** [comment]
Will take a look, tweak, and get it in. Thanks Preston for starting this!

**Comment by Jooms** [comment]
Ready for review @briswells and @prestonmasseyblake  (and any others that want to verify that the README instructions work)

**Review by Jooms — APPROVED** [review]

**Comment by briswells** [comment]
@Jooms @prestonmasseyblake I have updated the dummy data to include hashed passwords. This allows us to keep passport.js unchanged. I also reverted the changes to the readme as exporting env vars every time in not efficient. The .env approach will work for the backend whether running in docker or not. 

With this code plus the update in #127 the frontend will auto login when run with docker compose.

**Review by Jooms — APPROVED** [review]
@briswells changes look good to me

**Pull request merged**
