### PR TITLE
Merging frontend branch with main for rebase 

### PR DESCRIPTION
**Pull request by hardikpatil**
In this PR,  added Sales report icons in asset and merging frontend branch with main for rebase

### CODE REVIEW

**Review by prestonmasseyblake — APPROVED** [review]
great pull request

**Comment by DevangRaval1** [comment]
Review

LGTM

**Review by DevangRaval1 — APPROVED** [review]

**Comment by Jayesh-sathe** [comment]
hi all,
i am unnecessarily getting emails
pls remove my email from cc

**Comment by kbuffardi** [comment]
@Jayesh-sathe sorry about that. I'll remind the class not to tag you in issues. If you want to remove all notifications no matter what, you can also go to [the repo](https://github.com/ChicoState/PantryNode) and click the **Watch** dropdown and change it to **"Ignore"** and I believe that will suppress any emails, even if you're tagged.

**Pull request merged**
