### PR TITLE
Coverage report added, resolves #21

### LINKED ISSUE #21: Add testing scaffold
- [x] Add infrastructure for automated testing, with emphasis on unit testing and acceptance testing
- [x] Incorporate testing into DevOps instrumentation
- [x] Add CI workflow to run all tests for PR and for `main` branch
- [x] Add coverage report for all pulls to `main` along with a status badge in `README.md`

### PR DESCRIPTION
**Pull request by sourabhk25**
Tasks completed - 
1. Coverage report configuration added for all pull requests to main branch
2. Status badge added to README.md

Collaborated with @G1411

### CODE REVIEW

**Comment by TanviMahajan11** [comment]
Github action for Backend Testing is failing. Can you please check again.

**Comment by G1411** [comment]
@TanviMahajan11 the threshold for coverage is set to 100% and it's not being met, hence the action is failing.

**Review by TanviMahajan11 — APPROVED** [review]

**Review by rohitkarhadkar — APPROVED** [review]
coverage
LGTM!!!

**Comment by chetan2298** [comment]
We'll need to come back to this maybe.

**Comment by Anoushka444** [comment]
Changes proposed #185 For FE Coverage @G1411 @sourabhk25 @chetan2298 @TanviMahajan11

**Pull request merged**
