### PR TITLE
Added formik to register page. Fixed issue #123

### PR DESCRIPTION
**Pull request by SANDESHSOBARAD**

### CODE REVIEW

**Review by priyankavrao97 — APPROVED** [review]
Working as expected.

**Comment by DevangRaval1** [comment]
ReviewSandesh

Some problem with validation

**Comment by AbhinavReddy-Dev** [comment]
@SANDESHSOBARAD Can we have a "view password" icon inside the password field, also the "confirm password" field which re-confirms the password set?

**Comment by SANDESHSOBARAD** [comment]
> 

Yes, I will work on that.

**Comment by hardikpatil** [comment]
Looks good to me. Can you add the same `view password` icon inside the confirm password field

Screenshot 2023-04-11 at 17 18 58

**Review by abhilashSreenivasa — APPROVED** [review]
Looks good to me as well.

**Pull request merged**
