### PR TITLE
Add mirageJS support to mock API

### LINKED ISSUE #146: Add Mock API server on frontend

### PR DESCRIPTION
**Pull request by sathyanarayanan-v**
I have covered most of the pages to use MirageJS to mock APIs'. 

- I have mocked API for the following pages
     - Sale
     - Feed
     - Login

Currently MirageJS is enabled on prod. Once we feel that APIs are solid, we can enable it only on dev environment. 

Closes #146 

Docs for MirageJS - [Click here!](https://miragejs.com/)

### CODE REVIEW

**Review by xl26 — APPROVED** [review]

**Comment by sathyanarayanan-v** [comment]
@xl26, @hardikpatil, @prasannarajezzzy and @prestonmasseyblake  I have worked on pages which you folks raised a PR for. Please review if this is working on your end. 

This PR will **NOT** communicate to backend.  Instead, MirageJS simulates the backend services. 

Let's keep the discussion here moving forward for this PR to shed light to all of us who are involved.

**Review by hardikpatil — APPROVED** [review]
No issues on docker or local, works great, however, sorting on the expiring list has changed, I looked at the script, logic is still the same, weird. 

Screenshot 2023-04-13 at 12 35 23
Screenshot 2023-04-13 at 12 35 30

**Comment by hardikpatil** [comment]
> No issues on docker or local, works great, however, sorting on the expiring list has changed, I looked at the script, logic is still the same, weird.
> 
> Screenshot 2023-04-13 at 12 35 23 Screenshot 2023-04-13 at 12 35 30

on `npm start`

Screenshot 2023-04-13 at 12 52 24

**Comment by hardikpatil** [comment]
> @hardikpatil Right now, MirageJS is configured to work only on port `3000`. From the screenshots attached, I can see that you are testing the app in port `3002`. Can you please check if the app works fine on port `3000`?

worked on port 3000!

Screenshot 2023-04-13 at 14 14 14
Screenshot 2023-04-13 at 14 14 28

**Comment by AbhinavReddy-Dev** [comment]
Works for me in local, but throws cors error in codespaces and there seems to be a docker issue when running it in a container. I think the docker issue is independent of this feature.

**Review by AbhinavReddy-Dev — APPROVED** [review]

**Pull request merged**
