### PR TITLE
Docker module issue Closing #139

### PR DESCRIPTION
**Pull request by briswells**

### CODE REVIEW

**Review by jayrevolinskyjr — CHANGES_REQUESTED** [review]
I can confirm that it was a me issue before. I followed [these instructions](https://docs.tibco.com/pub/mash-local/4.3.0/doc/html/docker/GUID-BD850566-5B79-4915-987E-430FC38DAAE4.html) for cleaning out the containers, images, and volumes and then i ran `docker compose build --no-cache` and `docker compose up` and it works for me.

**Review by hardikpatil — APPROVED** [review]
Looks good, worked on my end. Finally!

Screenshot 2023-04-13 at 19 43 25

**Comment by hardikpatil** [comment]
> I tried `docker compose build --no-cache` and then `docker compose up`, but I am still receiving the 'Cannot find module 'sequelize'' error, even after cleansing my docker cache, containers, images, and volumes. I am not sure if this is a me issue or from the node modules. I also think we need to update the readme instructions for building. Sequelize issues

I faced this yesterday, I had to remove all images, all stopped containers and images 
`docker image prune -a`
`docker stop $(docker ps -a -q)`
`docker rm $(docker ps -a -q)`
`docker rmi $(docker images -q)`.

**Review by jayrevolinskyjr — APPROVED** [review]

**Comment by shubhamlatkar** [comment]
> > I tried `docker compose build --no-cache` and then `docker compose up`, but I am still receiving the 'Cannot find module 'sequelize'' error, even after cleansing my docker cache, containers, images, and volumes. I am not sure if this is a me issue or from the node modules. I also think we need to update the readme instructions for building. Sequelize issues
> 
> I faced this yesterday, I had to remove all images, all stopped containers and images `docker image prune -a` `docker stop $(docker ps -a -q)` `docker rm $(docker ps -a -q)` `docker rmi $(docker images -q)`.

@hardikpatil I wonder where do you got these docker commands from? 🤔 
They are very risky and should be used under adult supervision only 😆

**Review by ysiddhapura — APPROVED** [review]
Tested this branch with the changes, deleted old images, ran docker compose build --no-cache, and docker compose-up and runs for me!

**Comment by AbhinavReddy-Dev** [comment]
@briswells @shubhamlatkar Can you please let us know the right commands to build and run? Looks like adding `--no-cache` to build command works, but wanted to know if that is the right way of doing it and if there is a need to update the README to let everyone the change in commands to run the container.

**Comment by kbuffardi** [comment]
Thanks for your work on this. 
There are a *lot* of files changed here so there's a lot to review. It looks like some of it is just shifting files into different directories. However, can you please give us a breakdown of what changes are included (and why)?

To tag onto @AbhinavReddy-Dev's question, is the proposed solution to use the `--no-cache` option **one** time, or **every** time we rebuild/run docker? Along those lines, are there any different directions that should be updated in `README.md`?

**Comment by briswells** [comment]
> Thanks for your work on this. There are a _lot_ of files changed here so there's a lot to review. It looks like some of it is just shifting files into different directories. However, can you please give us a breakdown of what changes are included (and why)?
> 
> To tag onto @AbhinavReddy-Dev's question, is the proposed solution to use the `--no-cache` option **one** time, or **every** time we rebuild/run docker? Along those lines, are there any different directions that should be updated in `README.md`?

Most of the changes are just moving the code from backend into a src folder and updated paths. I update the dockerfile's to copy the tsconfig.json files to their respective containers, updated the mounts in docker-compose to be the src directories and updated the path in backend/package.json to reflect the update with src directory. 

Docker compose build --no-cache will only need to be run once to fix any issues with legacy code hanging around in places it's not suppose to be. After that you should only need to run ```docker compose build``` when a new node module is installed.

**Comment by jayrevolinskyjr** [comment]
The README on the main branch is lacking `docker compose build` as an instruction. I am of the mindset that we should _not_ include the pruning commands on the README since we will be assuming that anyone who clones a fresh repo will not have any dangling images or cache issues related to PantryNode.

**Comment by kbuffardi** [comment]
> I am of the mindset that we should _not_ include the pruning commands on the README since we will be assuming that anyone who clones a fresh repo will not have any dangling images or cache issues related to PantryNode.

100% agree and I'm hoping that the proposed solution only involves pruning images and clearing cache for people currently working on the project. I hope our solution is sustainable and simple. Moreover, as acknowledged in the discussion, those commands might be effective but they are a bit dangerous to suggest to *anyone who might want to work on the project in the future* -- they involve deleting *all* images/containers, even those that don't belong to the project. That can be particularly troublesome for people who are also using Docker on other projects.

But if that is a non-issue with the proposed solution... that's a good sign!

**Comment by briswells** [comment]
I’m going to merge this with main and open a new issue to update the readme, and rename docker containers to more appropriate names.

**Pull request merged**
