### PR TITLE
Created a Dockerfile to Containerize MVP. fixes #18

### LINKED ISSUE #18: Containerize MVP
- [ ] Use Docker to automate the build for the project, using the current dependencies and infrastructure
- [ ] Update the `README.md` to provide instructions on how to use the container(s)

### PR DESCRIPTION
**Pull request by shubhamlatkar**
1. Added Dockerfile to Containerize pantry node.
2. To test use following cmd:
`docker build -t node-container .`
`docker run -p 3000:3000 -it node-container`

### CODE REVIEW

**Comment by AbhinavReddy-Dev** [comment]
I think it will be a good idea to update the instructions in readme for building and running the container.

**Comment by shubhamlatkar** [comment]
> I think it will be a good idea to update the instructions in readme for building and running the container.

Done

**Review by sourabhk25 — APPROVED** [review]
LGTM

**Comment by AbhinavReddy-Dev** [comment]
Can we please merge this into the development branch initially? If you like the idea can you please open a pull request to the development branch?
Only requesting this to keep the main branch clean from the back and forth pull requests in the future.

**Review by decoles — APPROVED** [review]
Looks great!

**Comment by AbhinavReddy-Dev** [comment]
I am facing an issue running this locally
Screenshot 2023-02-28 at 11 39 22 AM
System: MacOS on ARM64

**Comment by shubhamlatkar** [comment]
> I am facing an issue running this locally
> Screenshot 2023-02-28 at 11 39 22 AM
> System: MacOS on ARM64

Hi @AbhinavReddy-Dev could you add the complete logs of err msg plz!!

**Comment by AbhinavReddy-Dev** [comment]
@shubhamlatkar Here is the log, please let me know if I have overlooked any error message.
`+] Building 20.3s (9/10)                                                                                                                                                                                                                                                                                    
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                                                    0.0s
 => => transferring dockerfile: 159B                                                                                                                                                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                                         0.0s
 => [internal] load metadata for docker.io/library/node:alpine                                                                                                                                                                                                                                          2.2s
 => [auth] library/node:pull token for registry-1.docker.io                                                                                                                                                                                                                                             0.0s
 => [1/5] FROM docker.io/library/node:alpine@sha256:667dc6ed8fc6623ccd21cb5fa355c90f848daaf5d6df96bc940869bfdf91c19a                                                                                                                                                                                    4.4s
 => => resolve docker.io/library/node:alpine@sha256:667dc6ed8fc6623ccd21cb5fa355c90f848daaf5d6df96bc940869bfdf91c19a                                                                                                                                                                                    0.0s
 => => sha256:b9c7c571278484011ce10210e5735389fb3fb3ac4fa6f13c08d5f80abe5595a4 48.00MB / 48.00MB                                                                                                                                                                                                        2.9s
 => => sha256:9d10200aa9cea543884bc85bc3bcf560ee14adbb4b919c962d79b7bfbd4e8552 2.41MB / 2.41MB                                                                                                                                                                                                          0.6s
 => => sha256:06ae8d8a7aa06f3132230cd7da725f6e86f84aaa3f67269a8697cb32d79bae59 449B / 449B                                                                                                                                                                                                              0.4s
 => => sha256:667dc6ed8fc6623ccd21cb5fa355c90f848daaf5d6df96bc940869bfdf91c19a 1.43kB / 1.43kB                                                                                                                                                                                                          0.0s
 => => sha256:0248e652e204b5af53ca39265d77eeaf0ec7bb966ca5255ce60587222d052c9c 1.16kB / 1.16kB                                                                                                                                                                                                          0.0s
 => => sha256:309fc9aaf0d7d138831483c33eae396be3e1b5bd83ac1e57e1b124f9300df1fc 6.45kB / 6.45kB                                                                                                                                                                                                          0.0s
 => => extracting sha256:b9c7c571278484011ce10210e5735389fb3fb3ac4fa6f13c08d5f80abe5595a4                                                                                                                                                                                                               1.1s
 => => extracting sha256:9d10200aa9cea543884bc85bc3bcf560ee14adbb4b919c962d79b7bfbd4e8552                                                                                                                                                                                                               0.1s
 => => extracting sha256:06ae8d8a7aa06f3132230cd7da725f6e86f84aaa3f67269a8697cb32d79bae59                                                                                                                                                                                                               0.0s
 => [internal] load build context                                                                                                                                                                                                                                                                       1.5s
 => => transferring context: 43.32MB                                                                                                                                                                                                                                                                    1.4s
 => [2/5] WORKDIR /app                                                                                                                                                                                                                                                                                  0.4s
 => [3/5] COPY package.json .                                                                                                                                                                                                                                                                           0.0s
 => ERROR [4/5] RUN npm install --only=prod                                                                                                                                                                                                                                                            13.1s
------                                                                                                                                                                                                                                                                                                       
 > [4/5] RUN npm install --only=prod:                                                                                                                                                                                                                                                                        
#9 0.539 npm WARN config only Use `--omit=dev` to omit dev dependencies from the install.                                                                                                                                                                                                                    
#9 11.39 npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1                                                                                                                                                                                                            
#9 11.40 npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer                                                                                                                                                                                                                               
#9 11.72 npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future                                                                                           
#9 11.74 npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
#9 11.88 npm WARN deprecated bcrypt@4.0.1: versions < v5.0.0 do not handle NUL in passwords properly
#9 12.91 npm notice 
#9 12.91 npm notice New patch version of npm available! 9.5.0 -> 9.5.1
#9 12.91 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.5.1>
#9 12.91 npm notice Run `npm install -g npm@9.5.1` to update!
#9 12.91 npm notice 
#9 12.91 npm ERR! code 1
#9 12.91 npm ERR! path /app/node_modules/bcrypt
#9 12.91 npm ERR! command failed
#9 12.91 npm ERR! command sh -c node-pre-gyp install --fallback-to-build
#9 12.91 npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/app/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
#9 12.91 npm ERR! node-pre-gyp info it worked if it ends with ok
#9 12.91 npm ERR! node-pre-gyp info using node-pre-gyp@0.14.0
#9 12.91 npm ERR! node-pre-gyp info using node@19.7.0 | linux | arm64
#9 12.91 npm ERR! node-pre-gyp WARN Using needle for node-pre-gyp https download 
#9 12.91 npm ERR! node-pre-gyp info check checked for "/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" (not found)
#9 12.91 npm ERR! node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v4.0.1/bcrypt_lib-v4.0.1-napi-v3-linux-arm64-musl.tar.gz
#9 12.91 npm ERR! node-pre-gyp http 404 https://github.com/kelektiv/node.bcrypt.js/releases/download/v4.0.1/bcrypt_lib-v4.0.1-napi-v3-linux-arm64-musl.tar.gz
#9 12.91 npm ERR! node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v4.0.1/bcrypt_lib-v4.0.1-napi-v3-linux-arm64-musl.tar.gz 
#9 12.91 npm ERR! node-pre-gyp WARN Pre-built binaries not found for bcrypt@4.0.1 and node@19.7.0 (node-v111 ABI, musl) (falling back to source compile with node-gyp) 
#9 12.91 npm ERR! node-pre-gyp http 404 status code downloading tarball https://github.com/kelektiv/node.bcrypt.js/releases/download/v4.0.1/bcrypt_lib-v4.0.1-napi-v3-linux-arm64-musl.tar.gz 
#9 12.91 npm ERR! gyp info it worked if it ends with ok
#9 12.91 npm ERR! gyp info using node-gyp@9.3.1
#9 12.91 npm ERR! gyp info using node@19.7.0 | linux | arm64
#9 12.91 npm ERR! gyp info ok 
#9 12.91 npm ERR! gyp info it worked if it ends with ok
#9 12.91 npm ERR! gyp info using node-gyp@9.3.1
#9 12.91 npm ERR! gyp info using node@19.7.0 | linux | arm64
#9 12.91 npm ERR! gyp ERR! find Python 
#9 12.91 npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
#9 12.91 npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
#9 12.91 npm ERR! gyp ERR! find Python checking if "python3" can be used
#9 12.91 npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
#9 12.91 npm ERR! gyp ERR! find Python checking if "python" can be used
#9 12.91 npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
#9 12.91 npm ERR! gyp ERR! find Python 
#9 12.91 npm ERR! gyp ERR! find Python **********************************************************
#9 12.91 npm ERR! gyp ERR! find Python You need to install the latest version of Python.
#9 12.91 npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#9 12.91 npm ERR! gyp ERR! find Python you can try one of the following options:
#9 12.91 npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#9 12.91 npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
#9 12.91 npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
#9 12.91 npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
#9 12.91 npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#9 12.91 npm ERR! gyp ERR! find Python For more information consult the documentation at:
#9 12.91 npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#9 12.91 npm ERR! gyp ERR! find Python **********************************************************
#9 12.91 npm ERR! gyp ERR! find Python 
#9 12.91 npm ERR! gyp ERR! configure error 
#9 12.91 npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
#9 12.91 npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
#9 12.91 npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
#9 12.91 npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
#9 12.91 npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
#9 12.91 npm ERR! gyp ERR! stack     at exithandler (node:child_process:427:5)
#9 12.91 npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:439:5)
#9 12.91 npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
#9 12.91 npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
#9 12.91 npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:483:16)
#9 12.91 npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
#9 12.91 npm ERR! gyp ERR! System Linux 5.15.49-linuxkit
#9 12.91 npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/app/node_modules/bcrypt/lib/binding/napi-v3" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
#9 12.91 npm ERR! gyp ERR! cwd /app/node_modules/bcrypt
#9 12.91 npm ERR! gyp ERR! node -v v19.7.0
#9 12.91 npm ERR! gyp ERR! node-gyp -v v9.3.1
#9 12.91 npm ERR! gyp ERR! not ok 
#9 12.91 npm ERR! node-pre-gyp ERR! build error 
#9 12.91 npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/app/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
#9 12.91 npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
#9 12.91 npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
#9 12.91 npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
#9 12.91 npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
#9 12.91 npm ERR! node-pre-gyp ERR! System Linux 5.15.49-linuxkit
#9 12.91 npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
#9 12.91 npm ERR! node-pre-gyp ERR! cwd /app/node_modules/bcrypt
#9 12.91 npm ERR! node-pre-gyp ERR! node -v v19.7.0
#9 12.91 npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.14.0
#9 12.91 npm ERR! node-pre-gyp ERR! not ok
#9 12.91 
#9 12.91 npm ERR! A complete log of this run can be found in:
#9 12.91 npm ERR!     /root/.npm/_logs/2023-02-28T19_35_53_417Z-debug-0.log
------
executor failed running [/bin/sh -c npm install --only=prod]: exit code: 1`

**Comment by shubhamlatkar** [comment]
> @shubhamlatkar Here is the log, please let me know if I have overlooked any error message. `+] Building 20.3s (9/10)
> 
> ## => [2/5] WORKDIR /app 0.4s
> => [3/5] COPY package.json . 0.0s
> => ERROR [4/5] RUN npm install --only=prod 13.1s
> > [4/5] RUN npm install --only=prod:
> > #9 0.539 npm WARN config only Use `--omit=dev` to omit dev dependencies from the install.
> > #9 11.39 npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
> > #9 11.40 npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
> > #9 11.72 npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
> > #9 11.74 npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
> > #9 11.88 npm WARN deprecated bcrypt@4.0.1: versions < v5.0.0 do not handle NUL in passwords properly
> > #9 12.91 npm notice
> > #9 12.91 npm notice New patch version of npm available! 9.5.0 -> 9.5.1
> > #9 12.91 npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.5.1
> > #9 12.91 npm notice Run `npm install -g npm@9.5.1` to update!
> > #9 12.91 npm notice
> > #9 12.91 npm ERR! code 1
> > #9 12.91 npm ERR! path /app/node_modules/bcrypt
> > #9 12.91 npm ERR! command failed
> > #9 12.91 npm ERR! command sh -c node-pre-gyp install --fallback-to-build
> > #9 12.91 npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/app/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
> > #9 12.91 npm ERR! node-pre-gyp info it worked if it ends with ok
> > #9 12.91 npm ERR! node-pre-gyp info using node-pre-gyp@0.14.0
> > #9 12.91 npm ERR! node-pre-gyp info using node@19.7.0 | linux | arm64
> > #9 12.91 npm ERR! node-pre-gyp WARN Using needle for node-pre-gyp https download
> > #9 12.91 npm ERR! node-pre-gyp info check checked for "/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" (not found)
> > #9 12.91 npm ERR! node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v4.0.1/bcrypt_lib-v4.0.1-napi-v3-linux-arm64-musl.tar.gz
> > #9 12.91 npm ERR! node-pre-gyp http 404 https://github.com/kelektiv/node.bcrypt.js/releases/download/v4.0.1/bcrypt_lib-v4.0.1-napi-v3-linux-arm64-musl.tar.gz
> > #9 12.91 npm ERR! node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v4.0.1/bcrypt_lib-v4.0.1-napi-v3-linux-arm64-musl.tar.gz
> > #9 12.91 npm ERR! node-pre-gyp WARN Pre-built binaries not found for bcrypt@4.0.1 and node@19.7.0 (node-v111 ABI, musl) (falling back to source compile with node-gyp)
> > #9 12.91 npm ERR! node-pre-gyp http 404 status code downloading tarball https://github.com/kelektiv/node.bcrypt.js/releases/download/v4.0.1/bcrypt_lib-v4.0.1-napi-v3-linux-arm64-musl.tar.gz
> > #9 12.91 npm ERR! gyp info it worked if it ends with ok
> > #9 12.91 npm ERR! gyp info using node-gyp@9.3.1
> > #9 12.91 npm ERR! gyp info using node@19.7.0 | linux | arm64
> > #9 12.91 npm ERR! gyp info ok
> > #9 12.91 npm ERR! gyp info it worked if it ends with ok
> > #9 12.91 npm ERR! gyp info using node-gyp@9.3.1
> > #9 12.91 npm ERR! gyp info using node@19.7.0 | linux | arm64
> > #9 12.91 npm ERR! gyp ERR! find Python
> > #9 12.91 npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
> > #9 12.91 npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
> > #9 12.91 npm ERR! gyp ERR! find Python checking if "python3" can be used
> > #9 12.91 npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
> > #9 12.91 npm ERR! gyp ERR! find Python checking if "python" can be used
> > #9 12.91 npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
> > #9 12.91 npm ERR! gyp ERR! find Python
> > #9 12.91 npm ERR! gyp ERR! find Python **********************************************************
> > #9 12.91 npm ERR! gyp ERR! find Python You need to install the latest version of Python.
> > #9 12.91 npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
> > #9 12.91 npm ERR! gyp ERR! find Python you can try one of the following options:
> > #9 12.91 npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
> > #9 12.91 npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
> > #9 12.91 npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
> > #9 12.91 npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
> > #9 12.91 npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
> > #9 12.91 npm ERR! gyp ERR! find Python For more information consult the documentation at:
> > #9 12.91 npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
> > #9 12.91 npm ERR! gyp ERR! find Python **********************************************************
> > #9 12.91 npm ERR! gyp ERR! find Python
> > #9 12.91 npm ERR! gyp ERR! configure error
> > #9 12.91 npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
> > #9 12.91 npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
> > #9 12.91 npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
> > #9 12.91 npm ERR! gyp ERR! stack     at PythonFinder. (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
> > #9 12.91 npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
> > #9 12.91 npm ERR! gyp ERR! stack     at exithandler (node:child_process:427:5)
> > #9 12.91 npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:439:5)
> > #9 12.91 npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
> > #9 12.91 npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
> > #9 12.91 npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:483:16)
> > #9 12.91 npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> > #9 12.91 npm ERR! gyp ERR! System Linux 5.15.49-linuxkit
> > #9 12.91 npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/app/node_modules/bcrypt/lib/binding/napi-v3" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
> > #9 12.91 npm ERR! gyp ERR! cwd /app/node_modules/bcrypt
> > #9 12.91 npm ERR! gyp ERR! node -v v19.7.0
> > #9 12.91 npm ERR! gyp ERR! node-gyp -v v9.3.1
> > #9 12.91 npm ERR! gyp ERR! not ok
> > #9 12.91 npm ERR! node-pre-gyp ERR! build error
> > #9 12.91 npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/app/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
> > #9 12.91 npm ERR! node-pre-gyp ERR! stack     at ChildProcess. (/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> > #9 12.91 npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
> > #9 12.91 npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
> > #9 12.91 npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
> > #9 12.91 npm ERR! node-pre-gyp ERR! System Linux 5.15.49-linuxkit
> > #9 12.91 npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> > #9 12.91 npm ERR! node-pre-gyp ERR! cwd /app/node_modules/bcrypt
> > #9 12.91 npm ERR! node-pre-gyp ERR! node -v v19.7.0
> > #9 12.91 npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.14.0
> > #9 12.91 npm ERR! node-pre-gyp ERR! not ok
> > #9 12.91
> > #9 12.91 npm ERR! A complete log of this run can be found in:
> > #9 12.91 npm ERR!     /root/.npm/_logs/2023-02-28T19_35_53_417Z-debug-0.log
> 
> executor failed running [/bin/sh -c npm install --only=prod]: exit code: 1`

Hi @AbhinavReddy-Dev, seems for ARM64 there is an issue for with [Bcrypt Library](https://github.com/kelektiv/node.bcrypt.js/releases/download/v4.0.1/bcrypt_lib-v4.0.1-napi-v3-linux-arm64-musl.tar.gz).

I think if we update the bcrypt to >= 5.0.0 would fix the issue and we would be able to run the container natively on ARM64
[bcrypt-issue](https://github.com/ysjkof/muool-backend/issues/5)

So for now we need to run the docker with linux/AMD64. You can use following commands to run:
`docker build -t my-app --platform linux/amd64 .`
`docker run -p 3000:3000 my-app`

**Comment by AbhinavReddy-Dev** [comment]
Above suggestion works, thanks! 
But we have to move towards independent containerization for until the frontend and backend are ready to be integrated?

**Comment by shubhamlatkar** [comment]
> Above suggestion works, thanks!
> But we have to move towards independent containerization for until the frontend and backend are ready to be integrated?

Hi @AbhinavReddy-Dev, [docker-compose](https://github.com/shubhamlatkar/PantryNode/blob/%2318-containerize-MVP/docker-compose.yml) can be modified and used for frontend and backend containers.

**Comment by shubhamlatkar** [comment]
Closing PR and further progress can be tracked on the [new PR](https://github.com/ChicoState/PantryNode/pull/34) on featured branch!!

**Pull request closed without merging**
