### PR TITLE
Stock Summary Page 

### PR DESCRIPTION
**Pull request by decoles**
Ready to move summary page to main without backend functionality, using pre-made data.

- Fits on mobile and desktop
- Self limiting tables (no long pages)
- Easily switch between tables and charts
- Themed charts and tables

### CODE REVIEW

**Comment by hardikpatil** [comment]
Need rebase

**Comment by AbhinavReddy-Dev** [comment]
@abhilashSreenivasa Can you please resolve the `package.json` errors in local and `npm install` gain to auto resolve `package-lock.json` errors and push code to the feature branch?

**Comment by abhilashSreenivasa** [comment]
> @abhilashSreenivasa Can you please resolve the `package.json` errors in local and `npm install` gain to auto resolve `package-lock.json` errors and push code to the feature branch?

Fixed

**Comment by hardikpatil** [comment]
@decoles @abhilashSreenivasa  On local, look great

Screenshot 2023-04-13 at 12 56 06
Screenshot 2023-04-13 at 12 56 14

however, when I run the container, renders the old interface

Screenshot 2023-04-13 at 15 16 04

**Comment by xl26** [comment]
@hardikpatil try rm all the images using -f. Might work.

**Comment by hardikpatil** [comment]
@abhilashSreenivasa @decoles also, put `active` on table tab as table showing default. Active reflecting,after toggle. 

Screenshot 2023-04-13 at 15 25 23

**Comment by AbhinavReddy-Dev** [comment]
> @abhilashSreenivasa @decoles also, put `active` on table tab as table showing default. Active reflecting,after toggle.
> 
> Screenshot 2023-04-13 at 15 25 23

Also some margin bottom for the tabs, if possible, can the tabs be of width 100%? Everything else looks great! Great work both of you!

**Comment by abhilashSreenivasa** [comment]
> @abhilashSreenivasa @decoles also, put `active` on table tab as table showing default. Active reflecting,after toggle.

Added default toggle.

**Comment by abhilashSreenivasa** [comment]
> Also some margin bottom for the tabs, if possible, can the tabs be of width 100%? Everything else looks great! Great work both of you!

Margin-bottom has been added.

**Comment by AbhinavReddy-Dev** [comment]
I have made some updates to the UI, Please check and let me know if you'd want to include them in the summary page.
https://github.com/ChicoState/PantryNode/blob/frontend_exp_summary/PantryNodeReact/src/pages/summary.tsx 

Screenshot 2023-04-13 at 4 05 02 PM

**Comment by AbhinavReddy-Dev** [comment]
Or you can make the boxShadow to be a border radius and it will look like this.


Screenshot 2023-04-13 at 4 13 41 PM

Screenshot 2023-04-13 at 4 13 10 PM

**Review by AbhinavReddy-Dev — APPROVED** [review]
Works and looks great!

**Comment by abhilashSreenivasa** [comment]
> I have made some updates to the UI, Please check and let me know if you'd want to include them in the summary page. https://github.com/ChicoState/PantryNode/blob/frontend_exp_summary/PantryNodeReact/src/pages/summary.tsx Or you can make the boxShadow to be a border radius and it will look like this.
> 
> Screenshot 2023-04-13 at 4 13 41 PM
> 
> Screenshot 2023-04-13 at 4 13 10 PM

yeah looks cool. Can you add that

**Comment by abhilashSreenivasa** [comment]
> I have made some updates to the UI, Please check and let me know if you'd want to include them in the summary page. https://github.com/ChicoState/PantryNode/blob/frontend_exp_summary/PantryNodeReact/src/pages/summary.tsx Or you can make the boxShadow to be a border radius and it will look like this.

Looks cool. Can you add that?

**Pull request merged**
