### PR TITLE
Link SKU Lookup Feature to Database

### PR DESCRIPTION
**Pull request by jayrevolinskyjr**
This is the pull request related to #174

### CODE REVIEW

**Comment by jayrevolinskyjr** [comment]
SKUFeatureLookup

WIP UML Diagram - Blockers shown on diagram in red.

**Comment by jayrevolinskyjr** [comment]
The frontend barcode input form is confirmed to talk to the backend, this PR resolves subtask 1, 2, and 4 for #174. Another PR will be open to complete the SKU Lookup Feature Functionality.

**Review by briswells — APPROVED** [review]
After deleting the DB and recreating it, feature worked as expected. No output was visually show on website, but feature was show to be working via browser and backend console.

**Review by ysiddhapura — APPROVED** [review]
Looks good to me, tried a few barcode entries and the console seems to recognize barcodes from the PLU data and will show as product not found in the console through inspect element.    

image

**Pull request merged**
