### PR TITLE
Added test cases for Sale table

### PR DESCRIPTION
**Pull request by abhinaydruva**
This is a test to check if the SaleTable component correctly renders a table with the provided category data.

### CODE REVIEW

**Review by rohitkarhadkar — APPROVED** [review]
SaleTable
LGTM!!!

**Review by rohitraut18 — APPROVED** [review]
Looks good to me!
test abhinay

**Review by TanviMahajan11 — APPROVED** [review]
Working fine. 

Approving changes. 
image

**Review by shubhamlatkar — APPROVED** [review]
Working Fine
image

**Pull request merged**
