### PR TITLE
Feature/donar page static

### PR DESCRIPTION
**Pull request by kushalramakanth**
Developed Donar Page and 

- added donar creation form
- Created table of donars

### CODE REVIEW

**Review by hardikpatil — APPROVED** [review]
Looks good to me. Sorting works as well on datatable.

Screenshot 2023-04-06 at 14 05 26
Screenshot 2023-04-06 at 14 05 50
Screenshot 2023-04-06 at 14 05 57
Screenshot 2023-04-06 at 14 06 15

**Comment by DevangRaval1** [comment]
Everything works on my end too.

**Review by DevangRaval1 — DISMISSED** [review]
LGTM!

**Review by DevangRaval1 — APPROVED** [review]
As per the discussion with @kushalramakanth validations and redirection will be in a different PR

**Pull request merged**
