### PR TITLE
Added structure and example for backend API

### LINKED ISSUE #141: Scaffold back-end interface file/route structure
Since we're moving to an API-like interface for the back-end, it's necessary to scaffold the API route and file structure to ensure consistency for project-required endpoints.

### PR DESCRIPTION
**Pull request by MMurtey**
The backend team is moving toward an API-like model after discussion with the frontend team. This commit scaffolds the backend API so we're all following a similar format when building out endpoints for frontend use. Beyond a few routes, the committed code doesn't contain any real logic, but I did test that the example endpoints were being reached correctly with their relevant HTTP methods. 

Once we merge this into main, we can move onto adding a basic Header-based bearer token auth for API calls and and build out the endpoints for whatever the frontend team needs.

Closes #141

### CODE REVIEW

**Review by hamsaraj7106 — COMMENTED** [review]
How do I check the post, patch and delete requests

**Comment by MMurtey** [comment]
> How do I check the post, patch and delete requests

To test the example route you can use DevTools (I did this in Firefox) to send requests using different methods. Start up PantryNode and visit the endpoints referenced in /backend/src/routes/api/v1/employee.

**Review by hamsaraj7106 — APPROVED** [review]
Get requests are working as expected

**Review by briswells — APPROVED** [review]

**Comment by MMurtey** [comment]
@briswells @hamsaraj7106 My apologies for letting the last review go stale. I resolved the latest merge conflicts and I'll be watching this PR closely today - let's see if we can get this through before app.js changes again.

**Review by briswells — APPROVED** [review]

**Review by hamsaraj7106 — APPROVED** [review]

**Pull request merged**
