### PR TITLE
Consolidated Coverage Report for FE & BE 

### LINKED ISSUE #194: Consolidate documentation/reports with coverage
Currently, there is a dedicated `backend/docs` folder for project documentation, but I would like a consolidated docs folder that includes any relevant documentation *anywhere in the system*. We need to do the following

- [ ] Move `backend/docs` to a `docs` folder in the root directory
- [ ] Consolidate coverage analysis that commits a single html report to the `docs` folder:
    - [ ] The coverage analysis should run on Actions whenever a PR is created *OR* when there is a merge into main. However, the report should only be committed (and badge in `README.md` updated) when it is accepted into main.
    - [ ] Both backend and frontend coverage should be analyzed in a single report (not as separate scripts/tools, if it can be avoided)
    - [ ] Only typescript files that are in our repo (i.e. no libraries or third-party dependencies) should be analyzed

### PR DESCRIPTION
**Pull request by chetan2298**
PR to check github action behaviour

This PR combines FE and BE tests and coverage to run in a single job

### CODE REVIEW

**Comment by chetan2298** [comment]
This commit features a combined test and coverage report for FE and BE in a single job.

[T](https://github.com/ChicoState/PantryNode/pull/244/commits/786665b59bcf881d6620fec8de2d6b8370a79c31)

**Comment by chetan2298** [comment]
This commit combines FE and BE tests and coverage report in a single job

https://github.com/ChicoState/PantryNode/pull/244/commits/272295ad13d5ea3e732d8b624c09ab03991cd9cf

**Review by sourabhk25 — APPROVED** [review]
The code looks good to me. Combined coverage report and Separate Coverage reports were created in different folders as well.
Subtasks tested - 
a) Backend and Frontend single coverage report - 
image

b) Coverage Report folder created in docs folder - 
Screen Shot 2023-05-15 at 10 13 51 PM

c) Only typescript files should be scanned - 
image

**Review by G1411 — APPROVED** [review]
Screenshot 2023-05-15 at 10 46 01 PM

Just ran it and it looks like its hitting all the three points correctly!

**Pull request closed without merging**
