### PR TITLE
Removed mongoose: 5.9.11 from package.json as we are migrating to Postgre SQL

### PR DESCRIPTION
**Pull request by mmendan**
Removed mongoose: 5.9.11 from package.json as we are migrating to Postgre SQL

### CODE REVIEW

**Review by TJSidhu1 — APPROVED** [review]
The change looks fine to me.

**Comment by kbuffardi** [comment]
@DevangRaval1 

After pulling `main` and rerunning the container with `docker-compose build` and `docker-compose up`

```
node                   | Error: Cannot find module 'mongoose'
node                   | Require stack:
node                   | - /app/backend/models-old/Item.js
node                   | - /app/backend/routes/sale.js
node                   | - /app/backend/app.js
node                   | - /app/backend/bin/www
node                   |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
node                   |     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/app/backend/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
node                   |     at Function.Module._load (node:internal/modules/cjs/loader:934:27)
node                   |     at Module.require (node:internal/modules/cjs/loader:1157:19)
node                   |     at require (node:internal/modules/helpers:119:18)
node                   |     at Object.<anonymous> (/app/backend/models-old/Item.js:1:18)
node                   |     at Module._compile (node:internal/modules/cjs/loader:1275:14)
node                   |     at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
node                   |     at Object.require.extensions.<computed> [as .js] (/app/backend/node_modules/ts-node/src/index.ts:1608:43)
node                   |     at Module.load (node:internal/modules/cjs/loader:1133:32) {
node                   |   code: 'MODULE_NOT_FOUND',
node                   |   requireStack: [
node                   |     '/app/backend/models-old/Item.js',
node                   |     '/app/backend/routes/sale.js',
node                   |     '/app/backend/app.js',
node                   |     '/app/backend/bin/www'
node                   |   ]
node                   | }
node exited with code 1
node                   | 
node                   | > project@0.0.0 start
node                   | > npx ts-node bin/www
node                   | 
node                   | Error: Cannot find module 'mongoose'
node                   | Require stack:
node                   | - /app/backend/models-old/Item.js
node                   | - /app/backend/routes/sale.js
node                   | - /app/backend/app.js
node                   | - /app/backend/bin/www
node                   |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
node                   |     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/app/backend/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
node                   |     at Function.Module._load (node:internal/modules/cjs/loader:934:27)
node                   |     at Module.require (node:internal/modules/cjs/loader:1157:19)
node                   |     at require (node:internal/modules/helpers:119:18)
node                   |     at Object.<anonymous> (/app/backend/models-old/Item.js:1:18)
node                   |     at Module._compile (node:internal/modules/cjs/loader:1275:14)
node                   |     at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
node                   |     at Object.require.extensions.<computed> [as .js] (/app/backend/node_modules/ts-node/src/index.ts:1608:43)
node                   |     at Module.load (node:internal/modules/cjs/loader:1133:32) {
node                   |   code: 'MODULE_NOT_FOUND',
node                   |   requireStack: [
node                   |     '/app/backend/models-old/Item.js',
node                   |     '/app/backend/routes/sale.js',
node                   |     '/app/backend/app.js',
node                   |     '/app/backend/bin/www'
node                   |   ]
node                   | }
node exited with code 1
node                   | 
node                   | > project@0.0.0 start
node                   | > npx ts-node bin/www
node                   | 
```

**Comment by DevangRaval1** [comment]
@kbuffardi I was working with @mmendan yesterday to remove the dependancy. It was working fine for both of us then. I will take a look again. We might have missed something

**Comment by mmendan** [comment]
The Mongoose dependency has been added back to package.json - #138

**Pull request merged**
