### PR TITLE
Dynamically rendering sales table data

### PR DESCRIPTION
**Pull request by KishoreMenda**
contributors - @Gajjela-Koushik-Reddy @arshiya19

### CODE REVIEW

**Comment by hardikpatil** [comment]
I believe, you already have push this commit in `frontend` 3 hours ago

**Comment by KishoreMenda** [comment]
I made some more changes on top of existing code in sale.tsx. So I created
a PR for that.

Thanks.

**Review by hardikpatil — DISMISSED** [review]

**Comment by DevangRaval1** [comment]
Hey, if you guys can check Issue #102 we have already started working on it.

**Comment by AbhinavReddy-Dev** [comment]
> Hey, if you guys can check Issue #102 we have already started working on it.

@KishoreMenda @Gajjela-Koushik-Reddy @arshiya19 Please coordinate with @DevangRaval1 on how to take this forward as they have created an issue before this, I believe they do have some code to push. Again, please check the issues before jumping in to work on anything necessary so that the work is not duplicated and wasted in the end.

**Comment by Gajjela-Koushik-Reddy** [comment]
Okay, sure. Thanks for letting us know.On Apr 11, 2023 19:33, Abhinav Reddy ***@***.***> wrote:

Hey, if you guys can check Issue #102 we have already started working on it.

@KishoreMenda @Gajjela-Koushik-Reddy @arshiya19 Please coordinate with @DevangRaval1 on how to take this forward as they have created an issue before this, I believe they do have some code to push. Again, please check the issues before jumping in to work on anything necessary so that the work is not duplicated and wasted in the end.

**Review by hardikpatil — COMMENTED** [review]
For now, holding off approval on this PR since two team worked on same issue without each other knowledge.

**Pull request closed without merging**
