### PR TITLE
Linter error on frontend

### PR DESCRIPTION
**Pull request by hardikpatil**

### CODE REVIEW

**Review by jayrevolinskyjr — DISMISSED** [review]
Works on my end, it's interesting that the tab was causing an issue. I think the frontend is still outside the action workflow right?

**Comment by hardikpatil** [comment]
> Works on my end, it's interesting that the tab was causing an issue.

yeah, it was throwing this on `npm run lint`

Screenshot 2023-04-13 at 19 54 18

**Comment by jayrevolinskyjr** [comment]
This looks like a continuation of the [frontend updates](https://github.com/ChicoState/PantryNode/pull/140/commits), which is a massive pull request. It seems concerning that it's not running any of the workflows. My current guess is to wait until the frontend updates are merged.

**Review by jayrevolinskyjr — DISMISSED** [review]
Approving so that this is included with the action workflows being done on the [frontend updates](https://github.com/ChicoState/PantryNode/pull/140/commits)

**Comment by AbhinavReddy-Dev** [comment]
> This looks like a continuation of the [frontend updates](https://github.com/ChicoState/PantryNode/pull/140/commits), which is a massive pull request. The workflows are configured for pull requests to main and not the frontend branch. Why not just merge it with the frontend updates so that the action workflows run?

We actually wanted to test it with the workflow checks before squash merging into frontend, so that we don't have to make more commits to get it working.

**Comment by jayrevolinskyjr** [comment]
> > This looks like a continuation of the [frontend updates](https://github.com/ChicoState/PantryNode/pull/140/commits), which is a massive pull request. The workflows are configured for pull requests to main and not the frontend branch. Why not just merge it with the frontend updates so that the action workflows run?
> 
> We actually wanted to test it with the workflow checks before squash merging into frontend, so that we don't have to make more commits to get it working.

Right, when you say it you mean the frontend updates or the bugfix/frontend-lint branch? What I am saying is that workflows will not run on this pull request since that would require updating the current workflow actions to handle pull-requests to frontend instead of just main.

**Comment by AbhinavReddy-Dev** [comment]
> > > This looks like a continuation of the [frontend updates](https://github.com/ChicoState/PantryNode/pull/140/commits), which is a massive pull request. The workflows are configured for pull requests to main and not the frontend branch. Why not just merge it with the frontend updates so that the action workflows run?
> > 
> > 
> > We actually wanted to test it with the workflow checks before squash merging into frontend, so that we don't have to make more commits to get it working.
> 
> Right, when you say 'it' you mean the frontend updates or the bugfix/frontend-lint branch? What I am saying is that workflows will not run on this pull request since that would require updating the current workflow actions to handle pull-requests to frontend instead of just main.

"it" means this branch.

**Comment by AbhinavReddy-Dev** [comment]
But I think we need to add the workflows for `frontend` as well, it will reduce the number of commits that are made for one feature into `main`, better late than never I say.

**Comment by jayrevolinskyjr** [comment]
> But I think we need to add the workflows for `frontend` as well, it will reduce the number of commits that are made for one feature into `main`, better late than never I say.

Yeah, I updated it now. Should be good.

**Review by jayrevolinskyjr — APPROVED** [review]
Approved, based on the consideration that we will squash this into the frontend branch

**Comment by hardikpatil** [comment]
> This looks like a continuation of the [frontend updates](https://github.com/ChicoState/PantryNode/pull/140/commits), which is a massive pull request. The workflows are configured for pull requests to main and not the frontend branch. Why not just merge it with the frontend updates so that the action workflows run?

now it makes sense going through this conversation, why the workflow wasn't working. Nice

**Comment by hardikpatil** [comment]
> > But I think we need to add the workflows for `frontend` as well, it will reduce the number of commits that are made for one feature into `main`, better late than never I say.
> 
> Yeah, I updated it now. Should be good.

Thank you.

**Pull request merged**
