### PR TITLE
Added API Route for Feed closing #114

### PR DESCRIPTION
**Pull request by briswells**

### CODE REVIEW

**Review by hardikpatil — APPROVED** [review]
Not sure, what the slashes are or may be an escape case. 

Screenshot 2023-04-15 at 13 27 38

**Review by TJSidhu1 — COMMENTED** [review]
The code looks fine to me!

**Comment by briswells** [comment]
> The code looks fine to me!

Would you be able to approve the PR?

**Comment by AbhinavReddy-Dev** [comment]
> > The code looks fine to me!
> 
> Would you be able to approve the PR?

Will an item added also be in the feed api? I see that the ID is coming from trand_item_id.

**Comment by briswells** [comment]
> > > The code looks fine to me!
> > 
> > 
> > Would you be able to approve the PR?
> 
> Will an item added also be in the feed api? I see that the ID is coming from trand_item_id.

This was to implement the feed similar to the feed in the old version of the app. We can easily update it to include other data, but I think we would want to open a different issue for that.

**Comment by AbhinavReddy-Dev** [comment]
> Not sure, what the slashes are or may be an escape case.
> 
> Screenshot 2023-04-15 at 13 27 38

Yeah it is the same to me, need to look into it to remove the unnecessary '\'.

**Comment by AbhinavReddy-Dev** [comment]
> > Not sure, what the slashes are or may be an escape case.
> > Screenshot 2023-04-15 at 13 27 38
> 
> Yeah it is the same to me, need to look into it to remove the unnecessary ''.

It could be solved by parsing the response or using a replacer for '\'.

**Comment by AbhinavReddy-Dev** [comment]
@briswells I'm trying to modify and check the response of this api, but when I'm trying to do it on docker container, I am unable to see any changes happening to the application until I run the docker command again. The code is not binding to the docker, do you know of any commands to get it working as expected? Thank you!

**Comment by AbhinavReddy-Dev** [comment]
> @briswells I'm trying to modify and check the response of this api, but when I'm trying to do it on docker container, I am unable to see any changes happening to the application until I run the docker command again. The code is not binding to the docker, do you know of any commands to get it working as expected? Thank you!

Looks like an issue has been created https://github.com/ChicoState/PantryNode/issues/155#issue-1669629235

**Review by AbhinavReddy-Dev — APPROVED** [review]

**Comment by AbhinavReddy-Dev** [comment]
Hope you're squash merging this.

**Comment by briswells** [comment]
> Hope you're squash merging this.

Yeah, the merge commit you see was a squash merge.

**Pull request merged**
