### PR TITLE
Merging migrate-to-postgres, updating #23

### PR DESCRIPTION
**Pull request by briswells**
Please note this is only a semi stable version of the code. It is being committed early as other teams are unable to do work without being able to run the app. It it's current form several of the routes in sales.js have not been updated and may result in crashes. Parts of the /home route was also commented out but the route is functional. You should be able to run the app, and login with the current changes. All other features may or may not work.

### CODE REVIEW

**Comment by Jooms** [comment]
Thank you for creating this @briswells. I agree this is the best path forward given the broken-ness of the old db

**Comment by briswells** [comment]
I have updated to pull request to merge with the most recent containerization addition to main. Now the app runs with just docker compose up.

**Review by AbhinavReddy-Dev — DISMISSED** [review]
Docker compose runs fine but there is still some error with mongo client (I'm attaching the ss), I'm thinking it is not worth working on mongo error beyond this point. We can isolate the APIs and start working on them. Great work @briswells with the PostgreSQL setup!

Screenshot 2023-03-14 at 2 30 00 AM

**Comment by briswells** [comment]
> Docker compose runs fine but there is still some error with mongo client (I'm attaching the ss), I'm thinking it is not worth working on mongo error beyond this point. We can isolate the APIs and start working on them. Great work @briswells with the PostgreSQL setup!
> 
> Screenshot 2023-03-14 at 2 30 00 AM

Have you completely nuked your docker containers, including the volumes, and re-run docker compose up? I have not gotten any MongoDB error in my testing.

**Comment by briswells** [comment]
@AbhinavReddy-Dev Looks like my last update with the stock model made it so you'll need to redo the review. Very little of the main app changed since the stock model isn't even being used yet.

**Comment by AbhinavReddy-Dev** [comment]
> > Docker compose runs fine but there is still some error with mongo client (I'm attaching the ss), I'm thinking it is not worth working on mongo error beyond this point. We can isolate the APIs and start working on them. Great work @briswells with the PostgreSQL setup!
> > Screenshot 2023-03-14 at 2 30 00 AM
> 
> Have you completely nuked your docker containers, including the volumes, and re-run docker compose up? I have not gotten any MongoDB errors in my testing.

Maybe that's the reason, I'll confirm, thanks!

**Comment by AbhinavReddy-Dev** [comment]
> > > Docker compose runs fine but there is still some error with mongo client (I'm attaching the ss), I'm thinking it is not worth working on mongo error beyond this point. We can isolate the APIs and start working on them. Great work @briswells with the PostgreSQL setup!
> > > Screenshot 2023-03-14 at 2 30 00 AM
> > 
> > 
> > Have you completely nuked your docker containers, including the volumes, and re-run docker compose up? I have not gotten any MongoDB errors in my testing.
> 
> Maybe that's the reason, I'll confirm, thanks!

Works now!

**Review by AbhinavReddy-Dev — APPROVED** [review]

**Comment by briswells** [comment]
@Jooms How's it looking from your side; is there anything you've noticed stopping us from completing this merge into main?

**Review by Jooms — APPROVED** [review]
Approving with the understanding that more work is required for this, but without it we can't start a lot of other work. Thank you @briswells 

We need to make a list of what was disabled as part of this MR.
#61 For the models
#62 For the large files
#51 For README formatting

**Pull request merged**
