### PR TITLE
Adding testcases for frontend component

### PR DESCRIPTION
**Pull request by rohitkarhadkar**
Components:

- Success -> The purpose of these tests is to ensure that the "Success" component is functioning correctly and rendering the expected content.
- Index -> This test case checks if the Index page renders the sorted feed list and sorted expired feed list. It uses mock data for API calls and checks for the presence of specific text on the page.

### CODE REVIEW

**Comment by rohitkarhadkar** [comment]
success
Coverage report for success component

**Review by rohitraut18 — DISMISSED** [review]
I tried testing the files. They worked fine!
test case

**Review by chetan2298 — DISMISSED** [review]
Working as expected.

image

**Comment by rohitraut18** [comment]
Added one test file for testing the index component.! Coverage 100%
indextest

**Review by shubhamlatkar — APPROVED** [review]
LGTM
image

**Review by chetan2298 — APPROVED** [review]
Looks good to me!

image

**Pull request merged**
